### ISSUE TITLE
Inconsistent `.mutual_information` method

### ISSUE THREAD

**Issue by grfrederic** [cbg-ethz/bmi#140]
In our samplers `.mutual_information()` is a callable method, in tasks it is a `@property`. It would be nice for them to be consistent.

**Comment by pawel-czyz** [comment]
@grfrederic The reason for this is the following:
  - `ISampler` may need additional arguments to calculate mutual information (as we do with BMMs, which collect MC samples. Here one can potentially specify the required number of samples. I also recall that we used it in some discrete-continuous estimators where MI is analytically known as an infinite series and we truncate it after a given number of terms). 
  - `Task` is supposed to already know MI. I.e., for `ISampler` `.mutual_information(k)` may have complexity $\mathcal O(f(k))$ and for `Task` querying `.mutual_information` property is supposed to be $\mathcal O(1)$.
  - How about adding `.mutual_information()` to `Task` for consistency?

**Comment by pawel-czyz** [comment]
@grfrederic Closing this for now, as I don't see a good way of reconciling – but please reopen if you think we can do something more :slightly_smiling_face:
