### ISSUE TITLE
Changes to the manuscript

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/bmi#154]
- [x] Use the NeurIPS template.
- [x] Cite the variational estimators literature (Poole et al., Song and Ermon, McAllester and Stratos)
- [x] Benchmark with tasks created using the BMM models to have a table in the appendix.
- [x] Make Section 4 a Subsection 3.4. 
- [x] Revisit the introduction.
- [x] Revisit the discussion and link to the appendix for more results.
- [x] Answer NeurIPS checklist questions.
- [x] Update the arXiv version.

**Comment by a-marx** [comment]
From the extended review that we got, a few additional points might be good to address:
- [ ] Double check the reference the reviewer provided for Prop 10 (Haussler & Opper, 1997, Kolchinsky & Tracey, 2017)
- [ ] Can we provide more experiments with the Bayesian estimator? Perhaps run it on the benchmark with BMM models---just to showcase its limitations and advantages?
- [ ] Clarify the takeaway from Figure 4

**Comment by pawel-czyz** [comment]
Great work @grfrederic and @a-marx! The new version will appear on arXiv tomorrow morning, so I'm closing this issue :slightly_smiling_face:
