### ISSUE TITLE
How to generate High Mutual Information use muliti-noraml-dense distribution?

### ISSUE THREAD

**Issue by fengsxy** [cbg-ethz/bmi#170]
I want to implement a benchmark which is used in smile/mine.
What is look like below, I guess the code should have the same style with bmi.benchmark.tasks.task_multinormal_dense,
but when I set rho = 0.99999 to get high mutaul information, I get Nan data.

```python
def sample_correlated_gaussian(rho=0.5, dim=20, batch_size=128, cubic=None, device="cpu"):
    """Generate samples from a correlated Gaussian distribution with correlation rho."""
    x, eps = torch.chunk(torch.randn(batch_size, 2 * dim), 2, dim=1)
    y = rho * x + torch.sqrt(torch.tensor(1. - rho**2).float()) * eps
    if cubic:
        y = y ** 3
    return x.to(device), y.to(device)
```
What I met nan.
<img width="399" alt="image" src="https://github.com/user-attachments/assets/86db892c-cbae-4a90-a57d-606b54c34dd0">
<img width="352" alt="image" src="https://github.com/user-attachments/assets/24fbd42c-eb25-4c39-a909-c68c778635bd">

```python
off_diag = rho
dense_task = bmi.benchmark.tasks.task_multinormal_dense(dim_x=3, dim_y=3, off_diag=off_diag)
```

**Comment by pawel-czyz** [comment]
Hi, `bmi.benchmark.tasks.task_multinormal_dense` has parameter `off_diag`, which has non-trivial constraints: the matrix $C_{ij}(\rho) = \begin{cases} 1 &\text{ if } i = j \\ \rho &\text{ otherwise}  \end{cases}$ is positive-definite only for some values of $\rho$. This is highly non-trivial constraint and we should have updated the documentation...

If you want to generate many strong interactions, it will be probably better to use `bmi.benchmark.tasks.task_multinormal_lvm`, which has a guarantee to generate positive definite matrices. We describe this approach in [Appendix D.2 of the manuscript](https://proceedings.neurips.cc/paper_files/paper/2023/file/36b80eae70ff629d667f210e13497edf-Paper-Conference.pdf).

**Comment by fengsxy** [comment]
```python
def sample_correlated_gaussian(rho=0.5, dim=20, batch_size=128, cubic=None, device="cpu"):
    """Generate samples from a correlated Gaussian distribution with correlation rho."""
    x, eps = torch.chunk(torch.randn(batch_size, 2 * dim), 2, dim=1)
    y = rho * x + torch.sqrt(torch.tensor(1. - rho**2).float()) * eps
    if cubic:
        y = y ** 3
    return x.to(device), y.to(device)
```
Where can I find design of this, I guess the interation parameter is not same as bmi.benchmark.tasks.task_multinormal_lvm.
You know, there was a lot of test, they have a bencmark called staircase.

**Comment by fengsxy** [comment]
What I am trying to do is to validate estimators's expression on the extreme high mutual information from 5-13. I try the workflow first, that needs super complex setting, meeting numerous bugs. 

So I am trying to implement by the minde way.
Here I found some problem.
1. When I implement by the method: the GPU usage is 70G, I guess there is some design of memroy leaking.
<img width="618" alt="image" src="https://github.com/user-attachments/assets/e2dd23ae-e808-4cf7-9c17-9cc0c0672e48">

```python
strength = [200, 650, 1100, 1550, 2000]
    task_list  = []
    for s in strength:
        task = bmi.benchmark.tasks.task_multinormal_sparse(dim_x=3, dim_y=3, strength=s)
        half_cube_task = bmi.benchmark.tasks.transform_half_cube_task(task)
        spiral_cube_task = bmi.benchmark.tasks.transform_spiral_task(task)
                #change task_name
        task_name = f"multinormal_sparse_{s}"
        half_cube_task_name = f"half_cube_multinormal_sparse_{s}"
        spiral_cube_task_name = f"spiral_multinormal_sparse_{s}"
        half_cube_task.task_name = half_cube_task_name
        spiral_cube_task.task_name = spiral_cube_task_name
        task.task_name = task_name

        task_list.append(spiral_cube_task)
        task_list.append(half_cube_task)
        task_list.append(task)
    for task in task_list:

        print(task)

        sampler_task = task

        print(f"Task {sampler_task.name} with dimensions {sampler_task.dim_x} and {sampler_task.dim_y} mi: {sampler_task.mutual_information} ")

        results = evaluate_task(args, sampler_task)

        results_tasks[sampler_task.name] = results
        print(results_tasks)```
  I refer this link:https://github.com/MustaphaBounoua/minde/blob/main/src/baseline/eval_baselines.py

**Comment by pawel-czyz** [comment]
Would switching to Snakemake be a possible solution? E.g., [here](https://github.com/cbg-ethz/bmi/tree/main/workflows/benchmark/demo) there is an example workflow which can be used to generate data sets, save them to the disk, and run given estimators. This should limit the required memory (and also allow one to run multiple evaluations simultaneously when cluster is available, which is useful for large experimental designs) :slightly_smiling_face:

**Comment by pawel-czyz** [comment]
> ```python
> def sample_correlated_gaussian(rho=0.5, dim=20, batch_size=128, cubic=None, device="cpu"):
>     """Generate samples from a correlated Gaussian distribution with correlation rho."""
>     x, eps = torch.chunk(torch.randn(batch_size, 2 * dim), 2, dim=1)
>     y = rho * x + torch.sqrt(torch.tensor(1. - rho**2).float()) * eps
>     if cubic:
>         y = y ** 3
>     return x.to(device), y.to(device)
> ```
> 
> Where can I find design of this, I guess the interation parameter is not same as bmi.benchmark.tasks.task_multinormal_lvm. You know, there was a lot of test, they have a bencmark called staircase.

I don't think we have such a task in the benchmark. Probably the easiest option for adding it would be to implement the [`Sampler`](https://cbg-ethz.github.io/bmi/api/samplers/) interface. (Alternatively, I think that one could construct an equivalent task using `bmi.benchmark.tasks.task_multinormal_lvm`, but this would require some algebra to figure out the parameters giving equivalent behaviour.)

**Comment by fengsxy** [comment]
Thank you for your kind reply. My experiments show that task_multinormal_sparse does not match the code I shared with you. This discrepancy arises because I am using this model to train on the F-DIME model. 
https://arxiv.org/pdf/2305.20025

While the generated code remains stable, the BMI sparse code results in infinity. Therefore, I suspect that this code may be equivalent to a dense version. I will investigate further and provide feedback.

And I am curious about is f-dime implementation and smile implemetation in plan?

**Comment by pawel-czyz** [comment]
> While the generated code remains stable, the BMI sparse code results in infinity. Therefore, I suspect that this code may be equivalent to a dense version.

Hmmm, I do not know where the instability may come – would you mind sharing a code example? Perhaps it's a problem with the `float` precision when calculating the decomposition of the covariance matrix (which is then very close to being noninvertible), but I'm not really sure...

If I understand the code you shared, the idea is to have several independent pairs of Gaussian variables $(X_k, Y_k)$, such that $\mathrm{corr}(X_k, Y_k) = \rho$. This can be implemented as:

```python
from bmi.samplers import IndependentConcatenationSampler, BivariateNormalSampler

dimension = 10
correlation = 0.999

sampler = IndependentConcatenationSampler([BivariateNormalSampler(correlation) for _ in range(dimension)])
```

I see that there is also a parameter for a cubic transformation. This is probably the easiest to implement via:

```python

from bmi.samplers import TransformedSampler

sampler = ...  # E.g., the code above to generate a base sampler, to be transformed
transformed_sampler = TransformedSampler(sampler, transform_y=lambda y: y**3)
```

> And I am curious about is f-dime implementation and smile implementation in plan?

Thanks for sharing the paper! I was not aware of the $f$-DIME estimator. We haven't planned to add more neural estimators in the nearest future, with a current focus on [implementing more expressive distributions](https://arxiv.org/abs/2310.10240). We can however accept PRs with JAX-based implementations, I think :slightly_smiling_face:

**Comment by pawel-czyz** [comment]
Hi, closing this issue for now – if more help would be needed, please free to reopen! :slightly_smiling_face:
